name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Checkout server
        uses: actions/checkout@v4
        with:
          repository: cypress-realworld-app
          path: cypress-realworld-app
      - name: Install Server
        run: cd cypress-realworld-app && yarn install
      - name: Checkout test
        uses: actions/checkout@v4
        with:
           path: tests

      - name: Install Test
        run: cd .. && npm install

      - name: Run Tests
        run: |
          cd cypress-realworld-app && yarn dev &
          cd .. &&  npm run wdio
          
      - name: Generate Allure report
        if: always() 
        run: cd tests && npm run allure:report

      - name: Deploy Report to GitHub Pages
        if: always() 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./tests/reports/allure-reports
